from SemesterInfoView import SemesterInfoView
from SemesterListView import SemesterListView
from CourseListView import CourseListView
from CourseInfoView import CourseInfoView
from CriteriaListView import CriteriaListView
from CriteriaInfoView import CriteriaInfoView
from AssignmentListView import AssignmentListView
from AssignmentInfoView import AssignmentInfoView

